#include <stdio.h>
#include <string.h>

#

// Fonction pour comparer deux listes de chaînes de caractères
int comparer_listes(char *liste1[], int taille1, char *liste2[], int taille2) {
    // Vérifier si les tailles des deux listes sont différentes
    if (taille1 != taille2) {
        return 0; // Les listes sont différentes si les tailles sont différentes
    }

    // Comparer chaque élément des deux listes
    for (int i = 0; i < taille1; i++) {
        if (strcmp(liste1[i], liste2[i]) != 0) {
            return 0; // Les listes sont différentes si au moins un élément diffère
        }
    }

    // Si aucune différence n'a été trouvée, les listes sont identiques
    return 1;
}

int main() {
    // Définir deux listes de chaînes de caractères
    char *liste1[] = {
        "A LA CLAIRE FONTAINE",
        "A LA UNA",
        "AGANAN YISH",
        "AH VOUS DIRAI-JE MAMAN",
        "ALLE VOEGEL SIND SCHON DA",
        "ANEVA STO TRAPEZIMOU",
        "ANI COUNI CHAOUANI",
        "ANI MORE NUSE",
        "APALAIS MENESS",
        "AUSTOSAS SAULES DZIESMA",
        "BAMBALI BAMBA",
        "BASKIROS",
        "BEI DEM SHTETL",
        "BELLA CIAO",
        "BELLE QUI TIENS MA VIE",
        "BEMBASA",
        "BERCEUSE COSAQUE",
        "BESENA ROVENA",
        "BIDONVILLE",
        "BINGYOL",
        "BINT EL CHALABIYA",
        "BIZIM MAHALLE",
        "BONJOUR COMMENT CA VA",
        "BUKUROSHJA E LALES",
        "CAD E SIN DON TE SIN",
        "CAJORIJE SUKARIJE",
        "CARINITO",
        "CERCLE CIRCASSIEN",
        "CHAMIL",
        "CHANT D'AMOUR",
        "CHOCOLAT CHAUD",
        "CIGANOCHKA",
        "CULA JESAM",
        "D'R HANS IM SCHNOKELOCH",
        "DANS LA FORET LOINTAINE",
        "DANSE BAVAROISE",
        "DANSE DE RECRUTEMENT",
        "DANSE ROUMAINE",
        "DANSES HONGROISES",
        "DANSES IRLANDAISES",
        "DANSONS LA CAPUCINE",
        "DEDINO KOLO",
        "DEMEDIM MI",
        "DER MAIE",
        "DER MOND IST AUFGEGANGEN",
        "DIE GEDANKEN SIND FREI",
        "DIRI DIRI",
        "DNI TYZHNYA",
        "DOUCE FRANCE",
        "DRAGOUSTA MIA",
        "DREMLE MI SE",
        "DZIVOS ILGI NE TIK ILGI",
        "EDERLEZI/HIDERRELEZ",
        "EHE GIA PANAGIA",
        "EL AGUAJAL",
        "ELENKO",
        "ELENO KERKO",
        "EN TEN TINI",
        "ES SASS EIN KLEIN WILD VOEGELEIN",
        "ESA ENAI",
        "FELIZ NAVIDAD",
        "FILD VOLACH",
        "FLIC FLAC FLOC",
        "FOGGY DEW",
        "FREILACH BULGAR",
        "FRERE JACQUES",
        "GANKINO HORO",
        "GAUDEAMUS HODIE",
        "GREENSLEEVES",
        "HAJDE JANO",
        "HARMODIK VERBUNKOS",
        "HAVA NAGILA",
        "HYMNE A LA JOIE",
        "IL ETAIT UN PETIT HOMME",
        "IZGRYALA E MESECHINKA",
        "J'AI DU BON TABAC",
        "J'AI UN GROS NEZ ROUGE",
        "J'AIME LA GALETTE",
        "JAMBO BWANA",
        "JE FAIS LE TOUR DE MA MAISON",
        "JOVANO",
        "JOYEUX ANNIVERSAIRE",
        "KADU BUVA KADUJO",
        "KATIOUCHA",
        "KOBA KASATCHOK",
        "KOJAK CECEK-PERGOTO",
        "KOLOMYYKA",
        "KUSTINO ORO",
        "KUTU KUTU PENSE",
        "L'ARAIGNEE GIPSY",
        "LA FLACA",
        "LA LLORONA",
        "LA MARMOTTE",
        "LA POULE",
        "LA ROSE ET LE ROSIER",
        "LAC BALATON",
        "LALE",
        "LE COQ EST MORT",
        "LE FACTEUR N'EST PAS PASSE",
        "LE PAS DU CHEVAL",
        "LE RETOUR DES CIGOGNES",
        "LE ROCK'N'ROLL DES GALLINACES",
        "LE VIEUX MACDONALD A UNE FERME",
        "LENO MORI",
        "LES P'TITS PAPIERS",
        "LES PETITS POISSONS DANS L'EAU",
        "LEYLIM",
        "LIPKA",
        "MAGGIE",
        "MAKEDONSKO DEVOJCE",
        "MAMI WATA",
        "MARCHE D'O'NEILL",
        "MARCHE TSIGANE",
        "MAYMOUNA",
        "MISIRLOU",
        "MOJ DILBERE",
        "MOJ E BUKURA",
        "MOJA MALA CIGANKA",
        "MOLLA MAMAD JAAN",
        "MON AMANT DE SAINT-JEAN",
        "MON ANE",
        "MON BEAU SAPIN",
        "MON PETIT LAPIN A BIEN DU CHAGRIN",
        "MOUTH MUSIC",
        "MUEDER ICH WILL A DING",
        "NANE TSORA",
        "NEIGE BLANCHE",
        "NISKA BANJA",
        "NOEL JAZZ",
        "O SOLE MIO",
        "OIKOPEDO",
        "OJ NA GORI ZHITO",
        "ONE LOVE",
        "OTCHI CHIORNIE",
        "OVAKO SE BIBER SIJE",
        "OY SMEREKO",
        "OY TAM NA MORI NA SYNOMU",
        "OY U VISHNEVOMU SADU",
        "PAPIROSEN",
        "PASSE PASSERA",
        "PASTIRCE MLADO - LEPA ANKA KOLO VODI",
        "POD ONOM GOROM ZELENOM",
        "PORIZALA PALCHYK",
        "QAMIN ZANA",
        "QUE NOTRE ALSACE EST BELLE",
        "QUE SERA SERA",
        "QUIZAS",
        "RACENITSA",
        "RAGANAS MEITA",
        "RAMIZEM",
        "REIHE REIHE ROSE",
        "RONDEAU",
        "ROSA",
        "ROULEZ ROULEZ PETIT TRAIN",
        "SAMIOTISA",
        "SAR UMAD ZEMESTUN",
        "SAVEZ-VOUS PLANTER LES CHOUX",
        "SCARBOROUGH FAIR",
        "SECO GELIYOR",
        "SEDNA BABA",
        "SHCHEDRYK",
        "SHERELE",
        "SHIPS",
        "SHOSHOLOZA",
        "SI TU AS DE LA JOIE AU COEUR",
        "SIKHALELA IZWE LAKITHI",
        "SINANARI",
        "SIRBA",
        "SNIJEG PADE",
        "STAR OF THE COUNTY DOWN",
        "SUMMERTIME",
        "SWING VALSE",
        "SYMPATHIQUE",
        "TANGO",
        "TARANTELLA",
        "TESIYE",
        "TETE EPAULES GENOUX ET PIEDS",
        "THALASSA",
        "THE SHOALS OF HERRING",
        "TIKE TIKE TACKE",
        "TOURNE TOURNE PETIT MOULIN",
        "TSIYON",
        "TUMANKUQE",
        "TUMBALALAIKA",
        "TUTUYE",
        "UN ELEPHANT QUI SE BALANCAIT",
        "UN GRAND CERF",
        "UN PINGOUIN DU POLE NORD",
        "UN POQUITO CANTAS",
        "USKUDAR",
        "VALLEZIM SHQIPETAR",
        "VALSE MANOUCHE",
        "VALSE SUEDOISE",
        "VEM KAN SEGLA FORUNTAN VIND",
        "VENT FRAIS",
        "VERBOVAYA DOSHCHECHKA",
        "VERBUNKOS",
        "VIVE LE VENT",
        "VOLANDO VOY",
        "VOLE VOLE PAPILLON",
        "VRANJANSKI COCEK",
        "W MOIM OGRODECZKU",
        "WHY DON'T YOU DO RIGHT",
        "YA PIDU V DALEKI HORY",
        "YOSHKE YOSHKE",
        "ZIM KHOROTIK YAR",
        "ZOZULECHKA",
        "ZUHRINO KOLO"
    };

    char *liste2[] = {
            "ZUHRINO KOLO",
            "ZOZULECHKA",
            "ZIM KHOROTIK YAR",
            "YOSHKE YOSHKE",
            "WHY DON'T YOU DO RIGHT",
            "W MOIM OGRODECZKU",
            "VRANJANSKI COCEK",
            "VOLANDO VOY",
            "VIVE LE VENT",
            "VERBUNKOS",
            "VERBOVAYA DOSHCHECHKA",
            "VENT FRAIS",
            "VEM KAN SEGLA FORUNTAN VIND",
            "VALSE SUEDOISE",
            "VALSE MANOUCHE",
            "VALLEZIM SHQIPETAR",
            "USKUDAR",
            "UN POQUITO CANTAS",
            "UN GRAND CERF",
            "TUTUYE",
            "TUMBALALAIKA",
            "TUMANKUQE",
            "TSIYON",
            "TOURNE, TOURNE PETIT MOULIN",
            "TIKE TIKE TACKE",
            "THALASSA",
            "TETE EPAULES GENOUX ET PIEDS",
            "TESIYE",
            "TARANTELLA",
            "TANGO",
            "SWING VALSE",
            "SUMMERTIME",
            "SNIJEG PADE",
            "SIRBA",
            "SINANARI",
            "SI TU AS DE LA JOIE AU COEUR",
            "SHOSHOLOZA",
            "SHIPS",
            "SHERELE",
            "SHCHEDRYK",
            "SEDNA BABA",
            "SECO GELIYOR",
            "SCARBOROUGH FAIR",
            "SAMIOTISA",
            "ROULEZ ROULEZ PETIT TRAIN",
            "ROSA",
            "RONDEAU",
            "REIHE REIHE ROSE",
            "RAMIZEM",
            "RAGANAS MEITA",
            "RACENITSA",
            "QUIZAS",
            "QUE SERA SERA",
            "QUE NOTRE ALSACE EST BELLE",
            "POD ONOM GOROM ZELENOM",
            "PASTIRCE MLADO - LEPA ANKA KOLO VODI",
            "PASSE PASSERA",
            "PAPIROSEN",
            "OY U VISHNEVOMU SADU",
            "OY TAM NA MORI NA SYNOMU",
            "OY SMEREKO",
            "OVAKO SE BIBER SIJE",
            "OTCHI CHIORNIE",
            "OJ NA GORI ZHITO",
            "OIKOPEDO",
            "O SOLE MIO",
            "NISKA BANJA",
            "NANE TSORA",
            "MUEDER ICH WILL A DING",
            "MON BEAU SAPIN",
            "MON ANE",
            "MON AMANT DE SAINT-JEAN",
            "MOLLA MAMAD JAAN",
            "MOJA MALA CIGANKA",
            "MOJ E BUKURA",
            "MOJ DILBERE",
            "MISIRLOU",
            "MAYMOUNA",
            "MARCHE TSIGANE",
            "MARCHE D'O'NEILL",
            "MAMI WATA",
            "MAGGIE",
            "LES P'TITS PAPIERS",
            "LE VIEUX MACDONALD A UNE FERME",
            "LE ROCK'N'ROLL DES GALLINACES",
            "LE RETOUR DES CIGOGNES",
            "LE PAS DU CHEVAL",
            "LE FACTEUR N'EST PAS PASSE",
            "LE COQ EST MORT",
            "LAC BALATON",
            "LA POULE",
            "LA MARMOTTE",
            "LA LLORONA",
            "LA FLACA",
            "KUTU KUTU PENSE",
            "KUSTINO ORO",
            "KOLOMYYKA",
            "KOJAK CECEK-PERGOTO",
            "KOBA KASATCHOK",
            "KATIOUCHA",
            "KADU BUVA KADUJO",
            "JOYEUX ANNIVERSAIRE",
            "JOVANO",
            "JE FAIS LE TOUR DE MA MAISON",
            "J'AIME LA GALETTE",
            "J'AI UN GROS NEZ ROUGE",
            "J'AI DU BON TABAC",
            "HAVA NAGILA",
            "HARMODIK VERBUNKOS",
            "HAJDE JANO",
            "GAUDEAMUS HODIE",
            "GANKINO HORO",
            "FRERE JACQUES",
            "FREILACH BULGAR",
            "FOGGY DEW",
            "FILD VOLACH",
            "ESA ENAI",
            "ES SASS EIN KLEIN WILD VOEGELEIN",
            "EN TEN TINI",
            "ELENO KERKO",
            "ELENKO",
            "EDERLEZI/HIDERRELEZ",
            "DZIVOS ILGI NE TIK ILGI",
            "DRAGOUSTA MIA",
            "DOUCE FRANCE",
            "DNI TYZHNYA",
            "DIRI DIRI",
            "DIE GEDANKEN SIND FREI",
            "DER MOND IST AUFGEGANGEN",
            "DER MAIE",
            "DEMEDIM MI",
            "DEDINO KOLO",
            "DANSONS LA CAPUCINE",
            "DANSES IRLANDAISES",
            "DANSES HONGROISES",
            "DANSE ROUMAINE",
            "DANSE DE RECRUTEMENT",
            "DANSE BAVAROISE",
            "CULA JESAM",
            "CIGANOCHKA",
            "CHANT D'AMOUR",
            "CERCLE CIRCASSIEN",
            "CARINITO",
            "CAJORIJE SUKARIJE",
            "BONJOUR COMMENT CA VA",
            "BIZIM MAHALLE",
            "BINGYOL",
            "BESENA ROVENA",
            "BERCEUSE COSAQUE",
            "BEMBASA",
            "BELLE QUI TIENS MA VIE",
            "BEI DEM SHTETL",
            "BASKIROS",
            "AUSTOSAS SAULES DZIESMA",
            "APALAIS MENESS",
            "ANI MORE NUSE",
            "ANEVA STO TRAPEZIMOU",
            "ALLE VOEGEL SIND SCHON DA",
            "AH VOUS DIRAI-JE MAMAN",
            "AGANAN YISH",
            "A LA UNA",
            "A LA CLAIRE FONTAINE"
        };


    // Obtenir la taille des listes
    int taille1 = sizeof(liste1) / sizeof(liste1[0]);
    int taille2 = sizeof(liste2) / sizeof(liste2[0]);

    // Appeler la fonction pour comparer les listes
    if (comparer_listes(liste1, taille1, liste2, taille2)) {
        printf("Les listes sont identiques.\n");
    } else {
        printf("Les listes sont différentes.\n");
    }

    return 0;
}

